export const GET_SPONSORSHIPS_REQUEST = 'GET_SPONSORSHIPS_REQUEST';
export const GET_SPONSORSHIPS_REQUEST_SUCCESS = 'GET_SPONSORSHIPS_REQUEST_SUCCESS';
export const GET_SPONSORSHIPS_REQUEST_FAILURE = 'GET_SPONSORSHIPS_REQUEST_FAILURE';
